/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ClI6QpOPbtH
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function OrderPage() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-[#F5F5F5]">
      <header className="flex items-center h-16 px-4 border-b bg-white dark:bg-gray-800">
        <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
          <svg
            className=" w-6 h-6"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
            <path d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
            <path d="M8 14v.5" />
            <path d="M16 14v.5" />
            <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
            <path d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
          </svg>
          <span>Wild West Diner</span>
        </Link>
        <div className="flex items-center w-full gap-4 ml-auto">
          <form className="flex-1 sm:flex-initial">
            <div className="relative">
              <svg
                className=" absolute left-2.5 top-2.5 h-4 w-4 text-zinc-500 dark:text-zinc-400"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <circle cx="11" cy="11" r="8" />
                <path d="m21 21-4.3-4.3" />
              </svg>
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search dishes..."
                type="search"
              />
            </div>
          </form>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <h1 className="text-3xl font-bold tracking-tight">Our Menu</h1>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card>
            <CardContent>
              <img
                alt="Dish image"
                className="rounded-lg object-cover w-full aspect-square"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <h3 className="font-semibold tracking-tight mt-2">Cowboy Steak</h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400">A juicy steak grilled to perfection.</p>
              <div className="flex justify-between items-center mt-2">
                <span className="text-xl font-bold">$15.99</span>
                <Button variant="default">Order Now</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                alt="Dish image"
                className="rounded-lg object-cover w-full aspect-square"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <h3 className="font-semibold tracking-tight mt-2">Rancher's Salad</h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400">Fresh greens with a tangy dressing.</p>
              <div className="flex justify-between items-center mt-2">
                <span className="text-xl font-bold">$9.99</span>
                <Button variant="default">Order Now</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <img
                alt="Dish image"
                className="rounded-lg object-cover w-full aspect-square"
                height="200"
                src="/placeholder.svg"
                width="200"
              />
              <h3 className="font-semibold tracking-tight mt-2">Pioneer Pasta</h3>
              <p className="text-xs text-zinc-500 dark:text-zinc-400">Hearty pasta with a robust sauce.</p>
              <div className="flex justify-between items-center mt-2">
                <span className="text-xl font-bold">$12.99</span>
                <Button variant="default">Order Now</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
