name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Run install
        run: pnpm install

      - name: Run database migration if schema changed.
        run: pnpm migrate:run
        env:
          DATABASE_URL: postgres://postgres:d1E*bAa2c3d5b65F25efgBcbDbCcbbag@viaduct.proxy.rlwy.net:17341/railway

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 159.203.85.181
          username: root
          password: 6oXJK2£^02a
          port: 22
          script: |
            cd proj
            git pull
            pnpm run build:ws
            pm2 start
